name: Benchmark Golang Libraries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  Benchmark-Expression-Evaluation:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Dependencies
      run: | 
        echo "Download Dependencies"
        cd  /home/runner/work/benchmark/benchmark/expression-evaluation && go mod tidy
        cd  /home/runner/work/benchmark/benchmark/expression-evaluation && go mod vendor

    - name: Benchmark
      run: | 
        echo "Benchmark Expression Evaluation libraries"
        cd  /home/runner/work/benchmark/benchmark/expression-evaluation && go test -bench=. -benchmem -count 1 -benchtime=100x > results/results.out
  
  Benchmark-In-Memory-Cache:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Dependencies
      run: | 
        echo "Download Dependencies"
        cd  /home/runner/work/benchmark/benchmark/in-memory-cache && go mod tidy
        cd  /home/runner/work/benchmark/benchmark/in-memory-cache && go mod vendor

    - name: Benchmark
      run: | 
        echo "Benchmark In-Memory Cache libraries"
        cd  /home/runner/work/benchmark/benchmark/in-memory-cache && go test -bench=. -benchmem -count 1 -benchtime=100x > results/results.out

  Benchmark-JSON:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Dependencies
      run: | 
        echo "Download Dependencies"
        cd  /home/runner/work/benchmark/benchmark/json && go mod tidy
        cd  /home/runner/work/benchmark/benchmark/json && go mod vendor

    - name: Benchmark
      run: | 
        echo "Benchmark Json libraries"
        cd  /home/runner/work/benchmark/benchmark/json && go test -bench=. -benchmem -count 1 -benchtime=10x > results/results.out

  Benchmark-Sql-Builder:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Dependencies
      run: | 
        echo "Download Dependencies"
        cd  /home/runner/work/benchmark/benchmark/sql-builder && go mod tidy
        cd  /home/runner/work/benchmark/benchmark/sql-builder && go mod vendor

    - name: Benchmark
      run: | 
        echo "Benchmark sql-builder libraries"
        cd  /home/runner/work/benchmark/benchmark/sql-builder && go test -bench=. -benchmem -count 1 -benchtime=10x > results/results.out

  Benchmark-Synchronization-Techniques:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Dependencies
      run: | 
        echo "Download Dependencies"
        cd /home/runner/work/benchmark/benchmark/synchronization-techniques && go mod tidy
        cd /home/runner/work/benchmark/benchmark/synchronization-techniques && go mod vendor

    - name: Benchmark
      run: | 
        echo "Benchmark Synchronization Techniques"
        cd /home/runner/work/benchmark/benchmark/synchronization-techniques && go test -bench=. -benchmem -count 1 -benchtime=100x > results/results.out

  Benchmark-Worker-Pool:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Dependencies
      run: | 
        echo "Download Dependencies"
        cd /home/runner/work/benchmark/benchmark/worker-pool && go mod tidy
        cd /home/runner/work/benchmark/benchmark/worker-pool && go mod vendor

    - name: Benchmark
      run: | 
        echo "Benchmark Worker Pool libraries"
        cd /home/runner/work/benchmark/benchmark/worker-pool && go test -bench=. -benchmem -count 1 -benchtime=100x > results/results.out

